apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics
  namespace: gitops-system
  labels:
    # Match Prometheus's serviceMonitorSelector.matchLabels
    release: cluster-monitoring
spec:
  selector:
    matchLabels:
      # Labels for metrics Service
      app.kubernetes.io/name: argocd-metrics
  namespaceSelector:
    matchNames:
      - gitops-system
  endpoints:
    - port: metrics
