apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-certificate
  namespace: gitops-system
spec:
  secretName: argocd-ui-ingress-tls
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - GitOps
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: argocd.gitops.local
  # isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  #usages:
  #  - server auth
  #  - client auth
  dnsNames:
    - argocd.gitops.local
  #uris:
  #- spiffe://cluster.local/ns/sandbox/sa/example
  #ipAddresses:
  #- 192.168.0.5
  # Issuer references are always required.
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
