# Expected secret file

# apiVersion: v1
# kind: Secret
# metadata:
#   name: repo-secret
#   namespace: gitops-system
# type: Opaque
# data:
#   # Any non-empty string as username, Gitlab access token value as password
#   gitlab_username:
#   gitlab_password:
#   # acepi001cr01.azurecr.cn
#   acepi001cr01_username:
#   acepi001cr01_password:

apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: repo-secret-sync
  namespace: gitops-system
spec:
  vault:
    name: acepi001kv02
    object:
      contentType: application/x-json
      name: argocd-repo-credentials
      type: multi-key-value-secret
  output:
    secret:
      name: repo-secret
