apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: argocd-repo-server
          env:
            - name: ARGOCD_EXEC_TIMEOUT
              value: "300"
            - name: ARGOCD_GIT_ATTEMPTS_COUNT
              value: "5"
          env:
            - name: HTTP_PROXY
              value: http://10.60.99.50:3128
            - name: HTTPS_PROXY
              value: http://10.60.99.50:3128