apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: argocd-server
          # Run argocd-server in "insecure" mode to allow ingress to do TLS.
          command:
            - argocd-server
            - --insecure
            - --staticassets
            - /shared/app
          env:
            - name: HTTP_PROXY
              value: http://10.60.99.50:3128
            - name: HTTPS_PROXY
              value: http://10.60.99.50:3128