sonarqube:
  ingress:
    enabled: true
    hosts:
      - name: sonarqube.gitops.local
        path: /
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    tls:
      - hosts:
          - sonarqube.gitops.local
        secretName: sonarqube-ingress-tls
  initSysctl:
    enabled: false
  plugins:
    install: []
  persistence:
    enabled: true
    # storageClass: "azurefile"
    size: 5Gi
  # postgresql:
  #   size: 20Gi
  #   storageClass: "azurefile"
