apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certificate
  namespace: gitops-system
spec:
  secretName: ca-tls
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - GitOps
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: ca.gitops.local
  isCA: true
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  #usages:
  #  - server auth
  #  - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - ca.gitops.local
  #uris:
  #- spiffe://cluster.local/ns/sandbox/sa/example
  #ipAddresses:
  #- 192.168.0.5
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
