apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Admin Cluster
  - admin/argocd.yaml
  - admin/secrets.yaml
  - admin/argocd-notifications.yaml
  - admin/applicationset.yaml
  - admin/argocd-image-updater.yaml
  - admin/cert-manager.yaml
  - admin/certs.yaml
  - admin/ingress-nginx.yaml
  - admin/ingress.yaml
  - admin/trivy.yaml
  - admin/jenkins.yaml
  # - admin/admin-pvc.yaml
  # - admin/elastic-operator.yaml
  # - admin/sonarqube.yaml
  # - admin/nexus.yaml
  # - admin/elastic-stack.yaml
  # - admin/kube-prometheus-stack.yaml
  # - admin/velero.yaml
