apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-search
spec:
  version: 7.13.3
  nodeSets:
  - name: master-nodes
    count: 3
    config:
      node.roles: ["master"]
      xpack.ml.enabled: true
    # podTemplate:
    #   spec:
    #     containers:
    #     - name: elasticsearch
    #       env:
    #       - name: ES_JAVA_OPTS
    #         value: -Xms2g -Xmx2g
    #       resources:
    #         requests:
    #           memory: 4Gi
    #           cpu: 1
    #         limits:
    #           memory: 4Gi
  - name: data-nodes
    count: 3
    config:
      node.roles: ["data", "ingest", "ml", "transform"]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        resources:
          requests:
            storage: 5Gi
        accessModes:
          - ReadWriteMany
        # storageClassName: azurefile