apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/install.yaml # https://github.com/argoproj/argo-rollouts/releases/download/v1.0.4/install.yaml, remember to comment preserveUnknownFields: false
