apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/install.yaml # https://raw.githubusercontent.com/argoproj/argo-cd/v2.0.5/manifests/install.yaml
  - base/project-admin.yaml
  # - base/argocd-metrics.yaml
  # - base/argocd-repo-server-metrics.yaml
  # - base/argocd-server-metrics.yaml

patchesStrategicMerge:
  - overlays/argocd-cm.yaml
  - overlays/argocd-rbac-cm.yaml
  - overlays/argocd-server-service.yaml
  - overlays/rolebinding.yaml
  - overlays/argocd-server.yaml
  - overlays/argocd-repo-server.yaml
  - overlays/argocd-application-controller.yaml

namespace: gitops-system
