# https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins
# https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/VALUES_SUMMARY.md
# https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml
jenkins:
  persistence:
    size: "10Gi"
  controller:
    image: "goldginkgo/jenkins"
    tag: "0.1"
    # imagePullSecretName: regcred
    installPlugins: false
    jenkinsAdminEmail: admin@test.cn
    ingress:
      enabled: true
      apiVersion: networking.k8s.io/v1
      hostName: jenkins.gitops.local
      tls:
        - secretName: jenkins-ingress-tls
          hosts:
            - jenkins.gitops.local
    additionalExistingSecrets:
      - name: jenkins-admin-secret
        keyName: jenkins-pass
    # https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos
    # https://jenkins2.infra.aldicn.local/configuration-as-code/reference
    JCasC:
      securityRealm: |-
        local:
          allowsSignup: false
          enableCaptcha: false
          users:
          - id: "admin"
            name: "Jenkins Admin"
            password: "${jenkins-admin-secret-jenkins-pass}"
        # ldap:
        #   configurations:
        #     - groupSearchFilter:
        #         "(&(cn={0})(objectclass=group))"
        #       inhibitInferRootDN: false
        #       mailAddressAttributeName: "userPrincipalName"
        #       managerDN: "CN=svc_Azure_Jenkins,OU=Service Accounts,OU=ACE,OU=AzureChina,DC=GITOPS,DC=LOCAL"
        #       managerPasswordSecret: "${ldap-bind-credentials-password}"
        #       rootDN: "DC=GITOPS,DC=LOCAL"
        #       server: "ldap://10.224.0.2"
        #       userSearch: "sAMAccountName={0}"
        #   disableMailAddressResolver: false
        #   disableRolePrefixing: true
        #   groupIdStrategy: "caseInsensitive"
        #   userIdStrategy: "caseInsensitive"
      configScripts:
        welcome-message: |
          jenkins:
            systemMessage: Welcome to Jenkins server.
        maven: |
          tool:
            maven:
              installations:
                - name: "maven"
                  properties:
                    - installSource:
                        installers:
                          - maven:
                              id: "3.6.3"
        mailer: |
          unclassified:
            mailer:
              charset: "UTF-8"
              defaultSuffix: "@gitops.cn"
              smtpHost: "smtp.gitops.local"
              useSsl: false
              useTls: false
        global-library: |
          unclassified:
            globalLibraries:
              libraries:
                - defaultVersion: "master"
                  name: "jenkins-library"
                  retriever:
                    modernSCM:
                      scm:
                        git:
                          id: "jenkins-gitlab"
                          remote: "https://github.com/goldginkgo/jenkins-library.git"
                          traits:
                            - "gitBranchDiscovery"