# https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins
# https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/VALUES_SUMMARY.md
# https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml
jenkins:
  persistence:
    size: "10Gi"
  controller:
    image: "goldginkgo/jenkins"
    tag: "0.1.0"
    # imagePullSecretName: regcred
    installPlugins: false
    jenkinsAdminEmail: admin@test.cn
    ingress:
      enabled: true
      apiVersion: networking.k8s.io/v1
      hostName: jenkins.gitops.local
      tls:
        - secretName: jenkins-ingress-tls
          hosts:
            - jenkins.gitops.local
