# https://github.com/jenkinsci/helm-charts/tree/main/charts/jenkins
# https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/VALUES_SUMMARY.md
# https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml
jenkins:
  persistence:
    size: "10Gi"
  controller:
    image: "goldginkgo/jenkins"
    tag: "0.1"
    # imagePullSecretName: regcred
    installPlugins: false
    jenkinsAdminEmail: admin@test.cn
    ingress:
      enabled: true
      apiVersion: networking.k8s.io/v1
      hostName: jenkins.gitops.local
      tls:
        - secretName: jenkins-ingress-tls
          hosts:
            - jenkins.gitops.local
    additionalExistingSecrets:
      - name: jenkins-admin-secret
        keyName: jenkins-pass
    # https://github.com/jenkinsci/configuration-as-code-plugin/tree/master/demos
    # https://jenkins2.infra.aldicn.local/configuration-as-code/reference
    JCasC:
      securityRealm: |-
        local:
          allowsSignup: false
          enableCaptcha: false
          users:
          - id: "admin"
            name: "Jenkins Admin"
            password: "${jenkins-admin-secret-jenkins-pass}"