apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-system

resources:
  - base/install.yaml # https://raw.githubusercontent.com/argoproj-labs/argocd-notifications/v1.1.1/manifests/install.yaml

patchesStrategicMerge:
  - overlays/argocd-notifications-secret.yaml
  - overlays/argocd-notifications-cm.yaml
  - overlays/catelog.yaml # https://raw.githubusercontent.com/argoproj-labs/argocd-notifications/v1.1.1/catalog/install.yaml
