# generate admin.password using https://www.browserling.com/tools/bcrypt

# apiVersion: v1
# data:
#   admin.password: JDJhJDEwJEZ5d3NPZHFuajd3UFQxamkyVFJGYmViMHlZUm5nT0xMU21BLnJXelMweW9MMGNBN0xVUUx5
#   admin.passwordMtime: MjAyMS0wNS0yNlQwMDowMjoxM1o=
#   server.secretkey: QVpZTFRNaUZ0TWlzeW01WXZRRDJodXE0enBVUk91NXZUaXZlUFVCN3ByND0=
# kind: Secret
# metadata:
#   name: argocd-secret
# type: Opaque

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: gitops-system
spec:
  encryptedData:
    admin.password: AgAtElTCsIH/IccDlOKuC5Q6H2uctaKqhP4eixCG+9m/5RKbepH5Ra8OMvTj1vflaRauQORx/4bJJ/IjGxlTm0Rrfox1hxmo92y3GkNSd6bCdT1nocMv5wuw0OvDRNUChLMeSRWrSZfD0P3MODaJj7lxQD8FYWBOTy6xKy3L+oIXP8R+CEC+SfZHIjtMkgk9tUEIks61Q3gZBESNFqA/OpR+DUVB3/wq0oLvqLtkqQjXUdUkKOzRgDLSvgw3D4buEZBuVJX9R0LRcpDBGPXjHsAQegvFDMWQiar35MmwB3HaVlShni4EiABiiX12V/euZskROhRXrYmcBdzU73rs7TbnfrdHqolYMpaJ1JCYico8PMP8MWb0kLYfMVoSvcMvbtZrWxiT2L2g/Ft6KgNZXPte4e1+PTMUoDXF4VvejgXy/XT717VS2Rzs7NGxEthKAmbdxsxm5H1LeTPWr9Lq1WqDmTYGGFWFhIwvdmGmkiend+HV4QUkxiLcuVt/pOgK553auPkULvTkTVOCoMnW0o6j+9KD7q8IoQqnfK3KIOISZn3D0B1HcvsF23WzlqWcM9UXddNfC9tUprL5sh4vPf3DkWxpw+aTu9ESROytTPkAUQplgopq8jbz6uYA98Gt5Qw8hRgAS7lB/Ncxt/CQGb6uMBOAjTCcwELv2J0MPgAa9J3cmsdPr0PBAxLzItN9/CcRrmJSSFfHU/JDY45CNXNVCpiZcrgPcJPvW12OBI9FJLZ7JxUWRFZtWJ6sd5cRfBTx17d5aYoQvtP1hhI=
    admin.passwordMtime: AgBCywFat9nVMM1Xp+gMogKY+4arWjbVmSKmRyPVY//Nye+Obc/AYz/UFXPk18Wqq1sV0sAai1L9k01rgepUTuaXPLHhoPda9RjsAHG/3RDi3uGKY0+9hQMr58y1VzYPPxTO+zPi1QvZIZvYupBXT1s/0fz/SHxZG3MrlqNiATSfewgYXi4B8CsaY5punql3KPDWE8Bcf6OmFYKH/Itb07PLhod59PTCpIKkoPuLmUD75YT2JhmkkxD7tQvq8qV01iq49Mc5lov83aTEaZDFx+N28u8Or7DTfbK3hc0jrBv776RY22yG1lCej4kQTzeLIixcYUoqLcWLIlKXvvl/KIzAeZnr/OuBrHHKbYixZ36F/mEY4LaWBJ5M0AjdH3wwNV13RO9w3mR8E5H+W1MbC3Z0KmaRU7mKrF1AR8FkbZ+cIlvveHtkJ4Vr7NvqEMlIlYZ78ZVMHvos8tFg5Vuz9msrP3mFJXJZyMDF5wSOVQk/v9tRVnrDCeV13sjNVJeLqfB5PIcltN0gAKtyIpGekaHslV8DEjTw1HglMr8Elcoqcj0rvcCPzfLYM0yBFCwWPvuijyPaQP0kfsvURAfRxYLFQtM0qFJPoF1xsmZhAsCKSUHrS4YWz/RPuX5SN71w3tZfgvkO+6rSOTeVnL/8/AZCNNSB6vhTGJMYndroMCURHUm+MfA4f3IdpWgQ1z+AJ2WtlE8mXtTHbCrERujRgBZfPIP7Jg==
    server.secretkey: AgBqEuvxqcLBpnJLkZKTQdwPehMkupwUDZnuoVXWYv7cSmQre4fTQ7abpL+HblrWFR9V0ojTztSHnbvSJYP07CBocehpT17+jTafM9mh7956e4BgW9qqAr1ETZ5wxDJLEorP12rARcjflI8k3CtSRf3UxzEGyRrdMYZhdZ+d+JHYWXUOtISEa2icfubxtlW2gZ27wI+ToQaIDM7qhhAYbYpVqdFlWguesBXlgLQLiFtF34eVwgaKx201t/oFNTUOhF0bdj1iN+4GV14ZIy1jgVkmXgP018l1IlBuFllteBoC5C107iYVr2MyZBIb9zrff+19tqaEXU8QFimnf/ZxynDKEV7bKOxiiJUb8XPgW3FMHt7lwabU4R5fvHlxJOy3hrJH3mA7SYlVTQoi+lGri4L92IJMF1irerhNCeKDl8km6msBpPU8f7VT/8fC3nHFJV+TgaUkWPtIjoYw4/cE/1ntLdlSc7rd02q94G0SNcB8Y5nRB/S0TjYM3nljah1tXEk/t/m1vJXPdcqUr+ijunwnSQFliO/Ox2Rx31HR9Xv4Eau9tsxLWWrYajpWJzgTfmD1R5cQHIZJTes6sfilMAwEfTq75rcRobqpQPoUzevCCfiKe9ikWs403Np6F61dcxxiVSvh/szLY98hlaXzawqjExJk54tVjW/tGUA+FYTM0x9fsnmQQn9HcmG4hiMCGnhKPp8t04ZdaXmRzIrRPbuTh1SeA2SeyaBqNmt+MHvt4ig7FQHKKHerHvJQEw==
  template:
    metadata:
      name: argocd-secret
      namespace: gitops-system