# apiVersion: v1
# data:
#   jenkins-pass: xxxxxx
# kind: Secret
# metadata:
#   name: jenkins-admin-secret


apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins-admin-secret
  namespace: gitops-system
spec:
  encryptedData:
    jenkins-pass: AgAmc6R/iVoq/f8V9E1X5udTwMbUOeO8bXSxqWy0L6g6Fr9S3p5E88ZdCC4bUplQlRZYPSUJq6pjJR5XD/YNGOUhPqIRkk8BBAOKrkIyySks7kv6ZkGJZ6XJ18ajv4NIvZdtCXhLtbReTNdQEmfMUli1BUYvgTjEsXC8AXAl5cZ1355OfzOakEPfbEXythmz79Tvu/9Qyb7NAZsf1KanByiDXr83dzAknYcln4rBMLRJZ9D3K+cmSH1zpKU/9kU84vJfhkD6ZgcgkkITnUHd0Ell1uCUd4Eo1G4qcGYuyg76J38o1DS2xDAO3S0EGxiksX7G6YOhZQ5QGGDuvTvxCVFLuNMm/QdKwy+GsrF66J2ZrrxHxjUVPs/aLHyk7xnS6Qazz+LHtmWE3ot7bR5Vq/HimBHvktFpY2Lm/pYCGJ32xh29n/5yoITcrPGeTI8bZ7cHjTwec1a0vv6OCbArC07OMBFg92kfSAUeyr7fspyC0hbJqJ4hZteXjo3/h/1AYdCQhMMOcrNbI3zjQ10Vn9q5GUHFZnVJ5fphg65C9ipkfoPxfqkyUvtciwl0LBNXuobM9QMO6/q+oxqe1oa+Lh9dDMtFKQmf9PMnF62mZ/VM1nhlZUllW4HItv3Rc9rZwyenvrOoHLfDiAmE5+CthSrZYbLAB1OxUgL+SxMD20hdtIXRIA/RuntaOG/dyPzUJEKD0LoHiA==
  template:
    metadata:
      name: jenkins-admin-secret
      namespace: gitops-system