# apiVersion: v1
# data:
#   jenkins-pass: xxxxxx
# kind: Secret
# metadata:
#   name: jenkins-admin-secret


apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jenkins-admin-secret
  namespace: gitops-system
spec:
  encryptedData:
    jenkins-pass: AgAjbuD2yIDqD9rDVSRdVNotvZVdHXSbZF6uT78ynr0bM23zkQx00AYe6X6cnbz1nxMFhvHFGykEuUpdZMlPfeZoEEojJN2XKf93R86lELHKFvqERPwZXrNj62fPyY0jTas/RqhGvcQfNiOSiNiqo9ZpcrVEZ4b6ZpUrS8r25KYNvlQhHXktS1aC+y58MzPsg00KgExGIVNDAPNX7o5kKIEyqsV7NDfdQXujtUmUCG455ttjNIgicnXQPrc+lMO8jymzaTfOsyEj7yRW7+IspPhq0Ja0sA74gS2jOfQ9GyoKoLYWXkkskAVwr+8uLlNgKjmtsopMLKVF71+0pFXzl7qQxlwvByMaTAD5fPDJ68cmwbJhk0xjcl3bTKbwKcViBq2Es+n9aB9JqVyPClSxewL/3MM1LWp2d5+X+QmjMPlko5TfVLFP+t7k5+qdFA5sFBroYhU3tb8QpBrg01cVfTaDHlRWAjuhjX5S0ru2EbrbgY0Yy1oh05qfIP+V2Xh6fTvkUoE2anTLqzHKbLaY0zHqgbTFNeBdn4k6EBcjTIhNwpXnx1+BVwrvx9QdyKGFUsJYdPxiIVrEczXDEfzzhmQrcWjJ/f6mYyaNygxPJnf3lPYiRoYNPRAKNzMXegkXGYv19W7wdj4mA6MFvmct+hX0e87OhQ9DcHrgN5pBB6OTb8VHVhVTkYjAvNy+7Z4bL54RD9qR3w==
  template:
    metadata:
      name: jenkins-admin-secret
      namespace: gitops-system